apiVersion: v1
kind: Service
metadata:
  name: pgadmin-svc
  namespace: default
  labels:
    app: pgadmin
spec:
  ports:
  - name: pgadmin-port
    nodePort: 30165
    port: 80
    targetPort: 80
  selector:
    app: pgadmin
  type: NodePort
