apiVersion: v1
kind: PersistentVolume
metadata:
  name: openldap-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/openldap-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openldap-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-init-data
data:
  init.sh: |
    #!/bin/sh
    echo "Waiting for LDAP to start..."
    while ! ldapsearch -x -H ldapi:/// -b "dc=example,dc=org" -D "cn=admin,dc=example,dc=org" -w admin123 2>/dev/null | grep -q "numEntries"; do
      sleep 2
    done
    echo "Loading initial data..."
    ldapadd -x -H ldapi:/// -D "cn=admin,dc=example,dc=org" -w admin123 -f /tmp/initial.ldif
    touch /tmp/initialized
    sleep infinity
  initial.ldif: |
    dn: dc=example,dc=org
    objectClass: top
    objectClass: domain
    dc: example

    dn: ou=users,dc=example,dc=org
    objectClass: organizationalUnit
    ou: users

    dn: ou=groups,dc=example,dc=org
    objectClass: organizationalUnit
    ou: groups

    dn: cn=admin,dc=example,dc=org
    objectClass: organizationalRole
    cn: admin
---
apiVersion: v1
kind: Pod
metadata:
  name: openldap-pod
spec:
  containers:
  - name: openldap
    image: osixia/openldap:1.5.0
    env:
    - name: LDAP_ORGANISATION
      value: "My Company"
    - name: LDAP_DOMAIN
      value: "example.org"
    - name: LDAP_ADMIN_PASSWORD
      value: "admin123"
    - name: LDAP_CONFIG_PASSWORD
      value: "config123"
    # Enable TLS (recommended for production):
    #- name: LDAP_TLS
    #  value: "true"
    #- name: LDAP_TLS_CRT_FILENAME
    #  value: "tls.crt"
    #- name: LDAP_TLS_KEY_FILENAME
      value: "tls.key"
    ports:
    - containerPort: 389
    - containerPort: 636
    volumeMounts:
    - name: data
      mountPath: /var/lib/ldap
    - name: config
      mountPath: /etc/ldap/slapd.d

  - name: ldap-loader
    image: osixia/openldap:1.5.0
    command: ["/bin/sh", "/tmp/init.sh"]
    volumeMounts:
    - name: init-script
      mountPath: /tmp/init.sh
      subPath: init.sh
    - name: init-script
      mountPath: /tmp/initial.ldif
      subPath: initial.ldif
    - name: init-script
      mountPath: /tmp/initialized
    - name: data
      mountPath: /var/lib/ldap
    - name: config
      mountPath: /etc/ldap/slapd.d

  volumes:
  - name: init-script
    configMap:
      name: ldap-init-data
      defaultMode: 0777
  - name: data
    emptyDir: {}
  - name: config
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: openldap-service
spec:
  type: NodePort
  selector:
    app: openldap
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 636
      nodePort: 30636