# Oracle Express: https://localhost:31500/em  User: SYSTEM  Password: Oracle123  ContainerName: <Empty> DBNAME: XE
# Host: localhost   Port: 31521
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/oracle-data"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      securityContext:
        fsGroup: 54321
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /opt/oracle/oradata/XE && chown -R 54321:54321 /opt/oracle/oradata"]
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
      containers:
      - name: oracle-db
        image: container-registry.oracle.com/database/express:latest
        securityContext:
          runAsUser: 54321
        env:
        - name: ORACLE_PWD
          value: "Oracle123"
        - name: ORACLE_CHARACTERSET
          value: "AL32UTF8"
        - name: ORACLE_DATAFILE_DEST
          value: "/opt/oracle/oradata/XE"  # Explicit path
        ports:
        - containerPort: 1521
        - containerPort: 5500
        volumeMounts:
        - name: oracle-data
          mountPath: /opt/oracle/oradata
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: oracle-data
        persistentVolumeClaim:
          claimName: oracle-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-service
spec:
  type: NodePort
  selector:
    app: oracle-db
  ports:
    - name: tns
      protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 31521
    - name: em
      protocol: TCP
      port: 5500
      targetPort: 5500
      nodePort: 31500