apiVersion: v1
kind: PersistentVolume
metadata:
  name: oracle-pv
  labels:
    type: local
    app: oracle
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/oracle/oradata
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-pvc
  labels:
    app: oracle
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
