apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-data
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redmine-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/redmine-postgresql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-data-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redmine-postgresql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: redmine
  labels:
    app: redmine
spec:
  containers:
  - name: redmine
    image: redmine:latest
    env:
    - name: REDMINE_DB_POSTGRES
      value: "localhost"
    - name: REDMINE_DB_USERNAME
      value: "redmine"
    - name: REDMINE_DB_PASSWORD
      value: "redmine123"
    - name: REDMINE_DB_PORT
      value: "5432"
    - name: REDMINE_SECRET_KEY_BASE
      value: "supersecretkey"
    ports:
    - containerPort: 3000
    volumeMounts:
    - name: redmine-data
      mountPath: /usr/src/redmine/files
    readinessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 60  # Tempo maior para inicialização
      periodSeconds: 10
  - name: postgresql
    image: postgres:13
    env:
    - name: POSTGRES_USER
      value: "redmine"
    - name: POSTGRES_PASSWORD
      value: "redmine123"
    - name: POSTGRES_DB
      value: "redmine"
    volumeMounts:
    - name: redmine-postgresql
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: redmine-data
    persistentVolumeClaim:
      claimName: redmine-data-pvc
  - name: redmine-postgresql
    persistentVolumeClaim:
      claimName: redmine-postgresql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
spec:
  type: NodePort
  selector:
    app: redmine
  ports:
    - protocol: TCP
      port: 3000        # Porta interna do Service
      targetPort: 3000  # Porta do container
      nodePort: 30300   # Porta externa no host