apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http-port
      volumeMounts:
        - mountPath: /nginx-volume
          name: primeiro-volume
  volumes:
    - name: primeiro-volume
      persistentVolumeClaim:
        claimName: nginx-pvc
