apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/rabbitmq-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-pod
  labels:
    app: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:management  # ← Must use management tag
    env:
    - name: RABBITMQ_DEFAULT_USER
      value: "admin"
    - name: RABBITMQ_DEFAULT_PASS
      value: "admin123"
    - name: RABBITMQ_ERLANG_COOKIE
      value: "secretcookie"  # Required for clustering
    ports:
    - containerPort: 5672
    - containerPort: 15672
    volumeMounts:
    - name: rabbitmq-data
      mountPath: /var/lib/rabbitmq
  volumes:
  - name: rabbitmq-data
    persistentVolumeClaim:
      claimName: rabbitmq-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672
    - name: management
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672