---
# PersistentVolumeClaim for GitLab data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# PersistentVolumeClaim for PostgreSQL data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# PersistentVolumeClaim for Redis data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ConfigMap for GitLab configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-config
data:
  GITLAB_OMNIBUS_CONFIG: |
    external_url 'http://gitlab.local';
    gitlab_rails['gitlab_shell_ssh_port'] = 30022;
    postgresql['enable'] = false;
    gitlab_rails['db_host'] = 'postgresql';
    gitlab_rails['db_username'] = 'gitlab';
    gitlab_rails['db_password'] = 'gitlab-password';
    gitlab_rails['db_database'] = 'gitlabhq_production';
    redis['enable'] = false;
    gitlab_rails['redis_host'] = 'redis';
---
# Secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
stringData:
  POSTGRES_USER: gitlab
  POSTGRES_PASSWORD: gitlab-password
  POSTGRES_DB: gitlabhq_production
---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - image: postgres:13.6
        name: postgresql
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 5432
          name: postgresql
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: 5432
  selector:
    app: postgresql
  clusterIP: None
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:6.2.6
        name: redis
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
  clusterIP: None
---
# GitLab Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:15.11.3-ce.0
        name: gitlab
        env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: gitlab-config
              key: GITLAB_OMNIBUS_CONFIG
        ports:
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: gitlab-data
          mountPath: /etc/gitlab
          subPath: config
        - name: gitlab-data
          mountPath: /var/opt/gitlab
          subPath: data
        - name: gitlab-data
          mountPath: /var/log/gitlab
          subPath: logs
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "6Gi"
            cpu: "4"
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
---
# GitLab HTTP Service
apiVersion: v1
kind: Service
metadata:
  name: gitlab-http
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    name: http
  - port: 443
    targetPort: 443
    nodePort: 30443
    name: https
  selector:
    app: gitlab
---
# GitLab SSH Service
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
spec:
  type: NodePort
  ports:
  - port: 22
    targetPort: 22
    nodePort: 30022
    name: ssh
  selector:
    app: gitlab
