apiVersion: v1
kind: Pod
metadata:
  name: monitoring-stack
  labels:
    app: monitoring
spec:
  initContainers:
  - name: create-dirs
    image: busybox
    command: ["/bin/sh", "-c"]
    args:
      - |
        mkdir -p /mnt/grafana-data && 
        mkdir -p /mnt/prometheus-data && 
        chmod -R 777 /mnt/grafana-data && 
        chmod -R 777 /mnt/prometheus-data
    volumeMounts:
    - name: grafana-hostpath
      mountPath: /mnt/grafana-data
    - name: prometheus-hostpath
      mountPath: /mnt/prometheus-data
  containers:
  - name: prometheus
    image: prom/prometheus:latest
    ports:
    - containerPort: 9090
    volumeMounts:
    - name: prometheus-config
      mountPath: /etc/prometheus/prometheus.yml
      subPath: prometheus.yml
    - name: prometheus-hostpath
      mountPath: /prometheus
  - name: grafana
    image: grafana/grafana:latest
    ports:
    - containerPort: 3000
    env:
    - name: GF_SECURITY_ADMIN_USER
      value: "admin"
    - name: GF_SECURITY_ADMIN_PASSWORD
      value: "grafana123"
    volumeMounts:
    - name: grafana-hostpath
      mountPath: /var/lib/grafana
    - name: grafana-datasources
      mountPath: /etc/grafana/provisioning/datasources/datasource.yml
      subPath: datasource.yml
  volumes:
  - name: prometheus-config
    configMap:
      name: prometheus-config
  - name: grafana-datasources
    configMap:
      name: grafana-datasources
  - name: grafana-hostpath
    hostPath:
      path: /mnt/grafana-data
      type: DirectoryOrCreate
  - name: prometheus-hostpath
    hostPath:
      path: /mnt/prometheus-data
      type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://localhost:9090
      access: proxy
      isDefault: true
---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
spec:
  type: NodePort
  selector:
    app: monitoring
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
      nodePort: 30300
    - name: prometheus
      port: 9090
      targetPort: 9090
      nodePort: 30909