# couchdb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchdb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: couchdb
  template:
    metadata:
      labels:
        app: couchdb
    spec:
      containers:
      - name: couchdb
        image: couchdb:latest
        env:
        - name: COUCHDB_USER
          value: "couchdb"
        - name: COUCHDB_PASSWORD
          value: "couchdb"
        - name: COUCHDB_SECRET
          value: "couchdb"
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ERFLAG
          value: "-name couchdb@$(NODENAME).couchdb-service.default.svc.cluster.local"
        ports:
        - containerPort: 5984
          name: http
        - containerPort: 4369
          name: portmapper
        - containerPort: 9100
          name: cluster
        volumeMounts:
        - name: couchdb-data
          mountPath: /opt/couchdb/data
      volumes:
      - name: couchdb-data
        persistentVolumeClaim:
          claimName: couchdb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: couchdb-service
spec:
  clusterIP: None
  selector:
    app: couchdb
  ports:
  - port: 5984
    name: http
  - port: 4369
    name: portmapper
  - port: 9100
    name: cluster

---

apiVersion: v1
kind: Service
metadata:
  name: couchdb-public
spec:
  type: NodePort
  selector:
    app: couchdb
  ports:
  - port: 5984
    targetPort: 5984
    nodePort: 30984