apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-my-pod-persistent-volume-cloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard