apiVersion: v1
kind: Pod
metadata:
  name: pv-1
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /gcp-my-pod-persistent-volume
          name: gcp-pv
  volumes:
    - name: gcp-pv
      persistentVolumeClaim:
        claimName: gcp-my-pod-persistent-volume-cloud