apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
  labels:
    type: local
    app: cassandra
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/cassandra
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  labels:
    app: cassandra
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
