# influxdb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1  # 1 is default. We can remove this entry.
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:latest
        env:
        - name: DOCKER_INFLUXDB_INIT_MODE
          value: "setup"
        - name: DOCKER_INFLUXDB_INIT_USERNAME
          value: "influxdb"
        - name: DOCKER_INFLUXDB_INIT_PASSWORD
          value: "influxdb"
        - name: DOCKER_INFLUXDB_INIT_ORG
          value: "my.influxdb.org"
        - name: DOCKER_INFLUXDB_INIT_BUCKET
          value: "influxdb"
        - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          value: "influxdb"
        ports:
        - containerPort: 8086
          name: http
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb2
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-public
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 30086